<!-- GitHub Star -->
<a class="github-button" href="https://github.com/hihozhou/php-opencv" data-count-href="/hihozhou/php-opencv/stargazers" data-count-api="/repos/hexojs/hexo#stargazers_count" data-count-aria-label="# stargazers on GitHub" aria-label="Star hexojs/hexo on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/hihozhou/php-opencv/fork" data-count-href="/hihozhou/php-opencv/network" data-count-api="/repos/hexojs/hexo#forks_count" data-count-aria-label="# forks on GitHub" aria-label="Fork hexojs/hexo on GitHub">Fork</a>

